module.exports = [
  {
    item_name: "Income",
    amount: 650,
    date: "July 4, 2022",
    from: "Employer",
    category: "income",
  },
  {
    item_name: "Rent",
    amount: -600,
    date: "July 4, 2022",
    from: "landlord",
    category: "expense",
  },
  {
    item_name: "Savings",
    amount: -100,
    date: "July 4, 2022",
    from: "Chase",
    category: "expense",
  },
  {
    item_name: "Income",
    amount: 650,
    date: "July 18, 2022",
    from: "employer",
    category: "income",
  },
  {
    item_name: "Taxes",
    amount: -200,
    date: "July 12, 2022",
    from: "IRS",
    category: "expense",
  },
  {
    item_name: "Subscription",
    amount: -15,
    date: "July 13, 2022",
    from: "Spotify",
    category: "expense",
  },
  {
    item_name: "Miscellaneous",
    amount: -3,
    date: "July 20, 2022",
    from: "Lyft",
    category: "expense",
  },
  {
    item_name: "Miscellaneous",
    amount: -25,
    date: "July 20, 2022",
    from: "Yankee Stadium",
    category: "expense",
  },
  {
    item_name: "Miscellaneous",
    amount: -12,
    date: "July 20, 2022",
    from: "Chopotle",
    category: "expense",
  },
  {
    item_name: "Miscellaneous",
    amount: -1,
    date: "July 24, 2022",
    from: "The Whitney",
    category: "expense",
  },
  {
    item_name: "Miscellaneous",
    amount: -25,
    date: "July 29, 2022",
    from: "MOMA",
    category: "expense",
  },
  {
    item_name: "Miscellaneous",
    amount: -25,
    date: "July 31, 2022",
    from: "Yankee Stadium",
    category: "expense",
  },
];
